/**
 * SprachDost Scenario Library — 55 real-life German conversation situations.
 * Each scenario guides the AI avatar's role-play. Levels = recommended CEFR.
 */

export type Scenario = {
  id: string;
  title: string;
  icon: string;
  category: string;
  level: "A1" | "A2" | "B1" | "B2";
  description: string;
  /** exact situation briefing injected into the AI system prompt */
  goal: string;
  /** German words the partner should naturally introduce */
  vocab: string[];
  /** opening hint for the student */
  opener: string;
};

export const SCENARIO_CATEGORIES = [
  "Food & Drink",
  "Travel",
  "Daily Life",
  "Work & Study",
  "Health & Help",
  "Social",
  "Shopping",
  "Exam Prep",
] as const;

export const SCENARIOS: Scenario[] = [
  /* ───────────── 🍽️ FOOD & DRINK ───────────── */
  { id: "cafe", title: "Ordering at a Café", icon: "☕", category: "Food & Drink", level: "A1",
    description: "Order your drink, answer questions, pay and say goodbye.",
    goal: "You are a friendly barista in a German café. The student is a customer ordering a drink (and maybe food). Guide: greeting → order → offer food → state the price → say goodbye.",
    vocab: ["der Kaffee", "der Tee", "das Croissant", "möchten", "bitte", "die Rechnung", "zusammen", "danke"],
    opener: "Try: 'Ich möchte einen Kaffee, bitte.'" },
  { id: "restaurant", title: "Restaurant & the Bill", icon: "🍽️", category: "Food & Drink", level: "A2",
    description: "Book a table, order food, ask for the bill.",
    goal: "You are a waiter in a German restaurant. Flow: welcome + table → drinks → food order → everything okay? → the bill → goodbye.",
    vocab: ["der Tisch", "die Speisekarte", "bestellen", "schmecken", "die Rechnung", "zahlen", "Trinkgeld"],
    opener: "Try: 'Einen Tisch für zwei Personen, bitte.'" },
  { id: "streetfood", title: "Street Food Stand", icon: "🌭", category: "Food & Drink", level: "A1",
    description: "Quick order at an Imbiss — currywurst time!",
    goal: "You run a Currywurst food stand. Quick, casual, friendly chat: what to eat, spicy or not, price, small talk about the food.",
    vocab: ["die Currywurst", "die Pommes", "scharf", "mit/ohne", "lecker", "euro"],
    opener: "Try: 'Eine Currywurst mit Pommes, bitte.'" },
  { id: "supermarket", title: "At the Supermarket", icon: "🛒", category: "Food & Drink", level: "A1",
    description: "Find products, ask prices, checkout chat.",
    goal: "You are a supermarket employee. The student asks where products are, asks prices, and checks out at the register.",
    vocab: ["Wo ist…?", "die Milch", "das Brot", "der Preis", "teuer/billig", "Kasse", "die Tüte"],
    opener: "Try: 'Entschuldigung, wo ist die Milch?'" },
  { id: "bakery", title: "Morning at the Bakery", icon: "🥨", category: "Food & Drink", level: "A1",
    description: "Fresh Brötchen, Brezel — the German morning ritual.",
    goal: "You are a baker selling fresh bread in the morning. Offer types of bread/rolls, count items, prices.",
    vocab: ["das Brötchen", "die Brezel", "das Brot", "frisch", "noch etwas?", "Stück"],
    opener: "Try: 'Guten Morgen! Drei Brötchen, bitte.'" },
  { id: "dinner-friends", title: "Cooking with a Friend", icon: "🍳", category: "Food & Drink", level: "A2",
    description: "Plan and cook dinner together.",
    goal: "You are the student's housemate cooking together. Plan what to cook, divide tasks, chat casually about food likes/dislikes.",
    vocab: ["kochen", "das Rezept", "schneiden", "die Kartoffel", "das Gemüse", "Guten Appetit!"],
    opener: "Try: 'Was kochen wir heute?'" },

  /* ───────────── ✈️ TRAVEL ───────────── */
  { id: "airport", title: "Airport Check-in", icon: "✈️", category: "Travel", level: "A2",
    description: "Check in, luggage, gate questions.",
    goal: "You are the check-in agent at a German airport. Passport, luggage weight, window/aisle seat, gate info, boarding time.",
    vocab: ["der Flug", "der Pass", "das Gepäck", "der Sitzplatz", "das Gate", "pünktlich"],
    opener: "Try: 'Guten Tag, ich fliege nach Delhi.'" },
  { id: "train", title: "Buying a Train Ticket", icon: "🚆", category: "Travel", level: "A1",
    description: "DB counter: destination, time, price.",
    goal: "You work at the Deutsche Bahn ticket counter. Destination, one-way/return, departure time, platform number, price.",
    vocab: ["das Ticket", "einfach/hin und zurück", "der Bahnhof", "das Gleis", "abfahren", "ankommen"],
    opener: "Try: 'Ein Ticket nach München, bitte.'" },
  { id: "hotel", title: "Hotel Check-in", icon: "🏨", category: "Travel", level: "A2",
    description: "Reservation, breakfast times, wifi password…",
    goal: "You are the hotel receptionist. Reservation name, nights, breakfast, wifi, checkout time, small questions.",
    vocab: ["die Reservierung", "das Zimmer", "das Frühstück", "das WLAN", "auschecken", "der Schlüssel"],
    opener: "Try: 'Ich habe eine Reservierung auf den Namen…'" },
  { id: "directions", title: "Asking for Directions", icon: "🗺️", category: "Travel", level: "A1",
    description: "Lost in the city — links? rechts? geradeaus?",
    goal: "You are a helpful local on the street. The student asks how to get to places (station, museum, café). Give simple directions with left/right/straight.",
    vocab: ["Entschuldigung", "Wie komme ich…?", "links", "rechts", "geradeaus", "die Kreuzung"],
    opener: "Try: 'Wie komme ich zum Bahnhof?'" },
  { id: "taxi", title: "Taking a Taxi", icon: "🚕", category: "Travel", level: "A1",
    description: "Address, speed, stop here, pay.",
    goal: "You are a taxi driver. Ask address, chat a bit, announce arrival, state the fare.",
    vocab: ["die Adresse", "nach + Ort", "hier links/rechts", "halten", "das kostet", "danke"],
    opener: "Try: 'Zum Hauptbahnhof, bitte.'" },
  { id: "sightseeing", title: "Sightseeing in Berlin", icon: "📸", category: "Travel", level: "B1",
    description: "Landmarks, opinions, photos.",
    goal: "You tour Berlin with the student: Brandenburger Tor, Fernsehturm etc. Share fun facts, ask opinions, suggest photos.",
    vocab: ["die Sehenswürdigkeit", "das Wahrzeichen", "beeindruckend", "das Foto", "empfehlen", "früher"],
    opener: "Try: 'Was kann man in Berlin besichtigen?'" },
  { id: "car-rental", title: "Renting a Car", icon: "🚗", category: "Travel", level: "B1",
    description: "Choose a car, insurance, fuel policy, prices.",
    goal: "You are the car rental agent: model choice, days, insurance, fuel rules, deposit, price.",
    vocab: ["der Mietwagen", "die Versicherung", "der Tank", "die Kaution", "automatik/manuell", "pro Tag"],
    opener: "Try: 'Ich möchte ein Auto für drei Tage mieten.'" },

  /* ───────────── 🏠 DAILY LIFE ───────────── */
  { id: "apartment", title: "Viewing an Apartment", icon: "🏠", category: "Daily Life", level: "A2",
    description: "Rooms, rent, warm/kalt, when can you move in?",
    goal: "You show the student a WG/apartment: rooms, rent (warm/kaltmiete), deposit, house rules, move-in date.",
    vocab: ["die Wohnung", "die Miete", "das Zimmer", "die Kaution", "einziehen", "die Küche"],
    opener: "Try: 'Ist die Wohnung noch frei?'" },
  { id: "neighbours", title: "Meeting the Neighbours", icon: "👋", category: "Daily Life", level: "A1",
    description: "Introduce yourself — where from, job, hobbies.",
    goal: "You are a friendly neighbour meeting the student in the hallway. Classic intro exchange: name, origin, work/study, small talk.",
    vocab: ["Ich heiße…", "Ich komme aus Indien", "wohnen", "arbeiten", "netto", "Freut mich!"],
    opener: "Try: 'Hallo! Ich bin neu hier. Ich heiße…'" },
  { id: "post", title: "At the Post Office", icon: "📮", category: "Daily Life", level: "A2",
    description: "Send a package, weight, stamps.",
    goal: "You work at the post office. Package to India: weight, price options, stamps for letters, delivery time.",
    vocab: ["das Paket", "der Brief", "die Briefmarke", "schicken", "das Gewicht", "die Sendung"],
    opener: "Try: 'Ich möchte ein Paket nach Indien schicken.'" },
  { id: "bank", title: "Opening a Bank Account", icon: "🏦", category: "Daily Life", level: "B1",
    description: "Documents, account types, online banking.",
    goal: "You are the bank advisor. Discuss documents, student account, fees, online banking, card pickup.",
    vocab: ["das Konto", "die Karte", "die Gebühr", "das Online-Banking", "der Ausweis", "kostenlos"],
    opener: "Try: 'Ich möchte ein Konto eröffnen.'" },
  { id: "phone-shop", title: "Buying a SIM Card", icon: "📱", category: "Daily Life", level: "A2",
    description: "Plans, data, monthly price.",
    goal: "You sell SIM cards / phone plans. Discuss data volume, price per month, contract length, activation.",
    vocab: ["die SIM-Karte", "der Tarif", "das Datenvolumen", "pro Monat", "der Vertrag", "aktivieren"],
    opener: "Try: 'Ich brauche eine SIM-Karte mit vielen Daten.'" },
  { id: "laundry", title: "Laundromat Chat", icon: "🧺", category: "Daily Life", level: "A1",
    description: "Machines, coins, waiting small talk.",
    goal: "Casual chat at the laundromat: which machine is free, how it works, coins, waiting small talk about weather etc.",
    vocab: ["die Waschmaschine", "der Trockner", "das Waschmittel", "frei/besetzt", "warten", "das Geld"],
    opener: "Try: 'Ist diese Maschine frei?'" },
  { id: "landlord", title: "Calling the Landlord", icon: "📞", category: "Daily Life", level: "B1",
    description: "Heating broken! Complain politely, agree on repair.",
    goal: "You are the landlord. The student reports a problem (heating/water). Be a bit difficult — the student must politely insist and agree on repair date.",
    vocab: ["die Heizung", "kaputt", "reparieren", "der Termin", "dringend", "der Handwerker"],
    opener: "Try: 'Guten Tag, die Heizung in meiner Wohnung ist kaputt.'" },

  /* ───────────── 💼 WORK & STUDY ───────────── */
  { id: "job-interview", title: "Job Interview", icon: "💼", category: "Work & Study", level: "B1",
    description: "Strengths, experience, why this company?",
    goal: "You are the interviewer at a German company. Ask about the student's background, strengths, weaknesses, motivation. Keep questions level-appropriate.",
    vocab: ["die Erfahrung", "die Stärke", "das Team", "die Stelle", "sich bewerben", "das Gehalt"],
    opener: "Try: 'Guten Tag, danke für die Einladung.'" },
  { id: "first-day", title: "First Day at Work", icon: "🖥️", category: "Work & Study", level: "A2",
    description: "Meet colleagues, learn the routine.",
    goal: "You are the new colleague showing the student around: introductions, where things are, lunch plan, routine.",
    vocab: ["der Kollege", "das Büro", "die Mittagspause", "der Computer", "arbeiten", "kennenlernen"],
    opener: "Try: 'Hallo, ich bin neu hier. Ich heiße…'" },
  { id: "university", title: "University Enrollment", icon: "🎓", category: "Work & Study", level: "B1",
    description: "Documents, semester fees, courses.",
    goal: "You are at the university admissions office: documents, enrollment, semester ticket, course registration.",
    vocab: ["die Immatrikulation", "das Semester", "der Studiengang", "die Unterlagen", "anmelden", "der Kurs"],
    opener: "Try: 'Ich möchte mich für das Wintersemester einschreiben.'" },
  { id: "library", title: "At the Library", icon: "📚", category: "Work & Study", level: "A1",
    description: "Membership card, find books, opening hours.",
    goal: "You are the librarian: membership card, where German learning books are, borrowing rules, opening hours.",
    vocab: ["die Bibliothek", "das Buch", "ausleihen", "der Ausweis", "öffnen/schließen", "leise"],
    opener: "Try: 'Wo finde ich Bücher zum Deutschlernen?'" },
  { id: "group-project", title: "Group Project Meeting", icon: "🧑‍🤝‍🧑", category: "Work & Study", level: "B1",
    description: "Divide tasks, deadlines, ideas.",
    goal: "Plan a group project with the student: who does what, deadline, tools, ideas. Encourage suggestions & gentle disagreement.",
    vocab: ["die Aufgabe", "die Deadline", "die Idee", "teilen", "präsentieren", "zusammenarbeiten"],
    opener: "Try: 'Welche Aufgabe kann ich machen?'" },
  { id: "internship", title: "Internship Talk", icon: "📊", category: "Work & Study", level: "B1",
    description: "Intro + what you'll do + duration.",
    goal: "You interview the student for an internship: studies, skills, when they can start, how long, simple questions.",
    vocab: ["das Praktikum", "die Fähigkeit", "anfangen", "die Woche", "der Lebenslauf", "lernen"],
    opener: "Try: 'Ich möchte mich für das Praktikum bewerben.'" },
  { id: "sick-leave", title: "Calling in Sick", icon: "🤒", category: "Work & Study", level: "A2",
    description: "Call your boss — sick today, doctor's note.",
    goal: "The student calls you (their boss) to say they're sick. Discuss symptoms briefly, doctor's note (Krankschreibung), when back.",
    vocab: ["krank", "das Fieber", "der Arzt", "die Krankschreibung", "heute", "bald"],
    opener: "Try: 'Guten Morgen, ich bin heute leider krank.'" },

  /* ───────────── 🏥 HEALTH & HELP ───────────── */
  { id: "doctor", title: "At the Doctor", icon: "🩺", category: "Health & Help", level: "A2",
    description: "Describe symptoms, understand advice.",
    goal: "You are a doctor. Ask symptoms, how long, pain location. Give simple advice: rest, medicine, water. Student must describe symptoms.",
    vocab: ["die Schmerzen", "der Kopf", "der Hals", "das Fieber", "die Medizin", "Gute Besserung!"],
    opener: "Try: 'Ich habe seit zwei Tagen Kopfschmerzen.'" },
  { id: "pharmacy", title: "At the Pharmacy", icon: "💊", category: "Health & Help", level: "A1",
    description: "Something for headache / cold…",
    goal: "You are the pharmacist. The student needs medicine for common issues. Ask symptoms, recommend, dosage instructions.",
    vocab: ["die Tablette", "die Apotheke", "gegen", "nehmen", "täglich", "rezeptfrei"],
    opener: "Try: 'Haben Sie etwas gegen Kopfschmerzen?'" },
  { id: "emergency", title: "Emergency Call", icon: "🚨", category: "Health & Help", level: "B1",
    description: "112! Describe the emergency fast and clearly.",
    goal: "You are the emergency operator. Guide the student to give: what happened, where, how many people, their name/phone. Stay calm, ask short questions.",
    vocab: ["der Notfall", "der Unfall", "die Adresse", "verletzt", "sofort", "der Krankenwagen"],
    opener: "Try: 'Hilfe! Es gab einen Unfall in der…'" },
  { id: "lost-wallet", title: "Lost My Wallet", icon: "😰", category: "Health & Help", level: "A2",
    description: "Report it, describe what was inside.",
    goal: "You work at the lost & found office: what was lost, where/when, contents, contact details, what happens next.",
    vocab: ["verloren", "die Geldbörse", "die Karte", "das Geld", "wann/wo", "finden"],
    opener: "Try: 'Ich habe meine Geldbörse verloren.'" },
  { id: "police", title: "Asking Police for Help", icon: "👮", category: "Health & Help", level: "B1",
    description: "Report theft: what, when, where, description.",
    goal: "You are a police officer taking a report about a stolen phone/bag. Ask details: when, where, description, phone number.",
    vocab: ["die Polizei", "gestohlen", "melden", "die Beschreibung", "gegen + Zeit", "der Zeuge"],
    opener: "Try: 'Ich möchte einen Diebstahl melden.'" },
  { id: "gym", title: "Talking to a Gym Trainer", icon: "🏋️", category: "Health & Help", level: "A2",
    description: "Membership, goals, training plan.",
    goal: "You are a gym trainer: ask goals (muscle/fitness), experience, recommend exercises, membership options.",
    vocab: ["das Fitnessstudio", "trainieren", "der Muskel", "der Plan", "die Mitgliedschaft", "Gewichte"],
    opener: "Try: 'Ich möchte fitter werden.'" },

  /* ───────────── 🎉 SOCIAL ───────────── */
  { id: "birthday", title: "Birthday Party", icon: "🎂", category: "Social", level: "A1",
    description: "Congratulations, gifts, cake talk.",
    goal: "It's your birthday party! The student congratulates you, asks about the gift/chat, cake, nice casual fun conversation.",
    vocab: ["Alles Gute!", "das Geschenk", "der Kuchen", "die Party", "feiern", "das Jahr"],
    opener: "Try: 'Herzlichen Glückwunsch zum Geburtstag!'" },
  { id: "friends", title: "Making New Friends", icon: "🤝", category: "Social", level: "A1",
    description: "Meet at a language café: name, country, hobbies.",
    goal: "You meet the student at a Stammtisch/language café. Exchange: name, country, job/study, hobbies, phone number/Instagram.",
    vocab: ["Woher kommst du?", "das Hobby", "gerne", "Musik", "Sport", "Lass uns…"],
    opener: "Try: 'Hallo! Ich heiße… Und du?'" },
  { id: "dating", title: "First Date", icon: "💕", category: "Social", level: "B1",
    description: "Light, fun getting-to-know-you over coffee.",
    goal: "You are on a friendly first date in a café. Light questions: hobbies, food, music, travel dreams. Keep it tasteful and fun.",
    vocab: ["interessant", "die Musik", "reisen", "der Film", "mögen", "nervös"],
    opener: "Try: 'Schön, dass du gekommen bist!'" },
  { id: "weekend", title: "Weekend Plans", icon: "🌤️", category: "Social", level: "A2",
    description: "Was machst du am Wochenende?",
    goal: "Casual chat about weekend plans: what you're doing, invite the student along, agree on time/place.",
    vocab: ["das Wochenende", "am Samstag", "treffen", "Lust?", "wann/wo", "mitkommen"],
    opener: "Try: 'Was machst du am Wochenende?'" },
  { id: "sports", title: "Talking Sports", icon: "⚽", category: "Social", level: "A2",
    description: "Football, cricket vs Fußball banter.",
    goal: "You love football (Bayern fan!). Chat about favorite sports, team, playing vs watching, friendly cricket-vs-football banter.",
    vocab: ["der Fußball", "die Mannschaft", "das Spiel", "gewinnen", "spielen", "der Fan"],
    opener: "Try: 'Spielst du gerne Fußball?'" },
  { id: "invitation", title: "Inviting Someone Out", icon: "📩", category: "Social", level: "A2",
    description: "Invite to dinner/movie, fix time & place.",
    goal: "The student invites YOU to something (movie/dinner). React: sometimes free, sometimes busy — negotiate day/time/place.",
    vocab: ["Hast du Lust…?", "einladen", "morgen/abends", "leider", "stattdessen", "passt gut"],
    opener: "Try: 'Hast du Lust, mit mir ins Kino zu gehen?'" },
  { id: "smalltalk", title: "Elevator Small Talk", icon: "🛗", category: "Social", level: "A1",
    description: "Weather, weekend — the German art of small talk.",
    goal: "You share an elevator / office kitchen moment: weather, day, weekend, very short answers with follow-up questions.",
    vocab: ["das Wetter", "heute", "schön/kalt", "der Montag", "müde", "bis später"],
    opener: "Try: 'Schönes Wetter heute, oder?'" },

  /* ───────────── 🛍️ SHOPPING ───────────── */
  { id: "clothes", title: "Clothes Shopping", icon: "👕", category: "Shopping", level: "A1",
    description: "Sizes, colors, fitting room, price.",
    goal: "You are a shop assistant. Help the student find a shirt/jeans: size, color, fitting room, price, sale items.",
    vocab: ["die Größe", "die Farbe", "anprobieren", "die Umkleide", "im Angebot", "gefällt mir"],
    opener: "Try: 'Ich suche ein T-Shirt in Größe M.'" },
  { id: "electronics", title: "Electronics Store", icon: "🔌", category: "Shopping", level: "A2",
    description: "Laptop/phone advice: price, features…",
    goal: "You work in an electronics store. The student needs a laptop/phone: budget, features (battery, storage), comparison, warranty.",
    vocab: ["der Laptop", "der Akku", "der Speicher", "der Preis", "die Garantie", "empfehlen"],
    opener: "Try: 'Ich suche einen Laptop. Er soll nicht zu teuer sein.'" },
  { id: "fleamarket", title: "Flea Market Bargaining", icon: "🪙", category: "Shopping", level: "B1",
    description: "Handeln! Negotiate the price like a local.",
    goal: "You sell at a flea market. The student wants an item — they must negotiate the price with you. Start too high, make them bargain!",
    vocab: ["Wie viel kostet…?", "zu teuer", "der Preis", "Handeln", "günstig", "einverstanden"],
    opener: "Try: 'Wie viel kostet diese Lampe?'" },
  { id: "return-item", title: "Returning an Item", icon: "↩️", category: "Shopping", level: "A2",
    description: "Broken headphones — receipt?, exchange?",
    goal: "The student returns a broken item. You ask for the receipt, the problem, offer exchange instead of money back — they must insist politely.",
    vocab: ["umtauschen", "kaputt", "die Quittung", "das Geld zurück", "funktioniert nicht", "gestern gekauft"],
    opener: "Try: 'Ich möchte diese Kopfhörer zurückgeben.'" },
  { id: "shoes", title: "Shoe Store", icon: "👟", category: "Shopping", level: "A1",
    description: "Size, color, comfortable?",
    goal: "Shoe store visit: size (Schuhgröße 42 etc.), color, try them on, comfortable?, price, buy.",
    vocab: ["die Schuhe", "die Schuhgröße", "bequem", "passen", "zu klein/groß", "nehmen"],
    opener: "Try: 'Haben Sie diese Schuhe in Größe 42?'" },
  { id: "farmers-market", title: "Farmers Market", icon: "🍅", category: "Shopping", level: "A2",
    description: "Fresh veggies, per kilo prices, regional.",
    goal: "You are a farmer at the weekly market: fresh produce, price per kilo, seasonal talk, how much the student wants.",
    vocab: ["das Kilo", "frisch", "das Gemüse", "die Äpfel", "die Saison", "regional"],
    opener: "Try: 'Ein Kilo Äpfel, bitte.'" },

  /* ───────────── 🎓 EXAM PREP ───────────── */
  { id: "a1-speaking-1", title: "Goethe A1: Self Intro", icon: "🎓", category: "Exam Prep", level: "A1",
    description: "Sprechen Teil 1 — introduce yourself exam-style.",
    goal: "You are the Goethe A1 examiner for Sprechen Teil 1. The student must introduce themselves: name, country, language, job/study, hobbies. Ask 2-3 follow-ups. Gently simulate exam conditions.",
    vocab: ["Ich heiße…", "Ich komme aus…", "Ich wohne in…", "Ich arbeite als…", "Meine Hobbys sind…"],
    opener: "Try: 'Ich heiße …, ich komme aus Indien…'" },
  { id: "a1-speaking-2", title: "Goethe A1: Theme Cards", icon: "🃏", category: "Exam Prep", level: "A1",
    description: "Teil 2 — speak about a theme (Essen, Familie…).",
    goal: "You are the Goethe A1 examiner for Sprechen Teil 2. Give a theme card (e.g. Essen, Familie, Freizeit). The student says 3-4 sentences. Ask related simple questions.",
    vocab: ["zum Beispiel", "meine Familie", "am liebsten", "weil", "jeden Tag", "oft"],
    opener: "Try: Start with any simple sentence, e.g. 'Meine Familie ist groß.'" },
  { id: "a1-speaking-3", title: "Goethe A1: Make Requests", icon: "🙋", category: "Exam Prep", level: "A1",
    description: "Teil 3 — ask your partner for things.",
    goal: "You are the exam partner for Teil 3. The student must make requests with picture prompts (e.g. window open, pen, photo). Expect 'Können Sie/Kannst du…?' Answer naturally.",
    vocab: ["Können Sie…?", "Kannst du…?", "das Fenster", "öffnen", "das Foto", "machen"],
    opener: "Try: 'Könnten Sie bitte das Fenster öffnen?'" },
  { id: "a2-speaking-1", title: "Goethe A2: About You", icon: "🗣️", category: "Exam Prep", level: "A2",
    description: "Sprechen Teil 1 — talk about a topic about yourself.",
    goal: "You are the Goethe A2 examiner Teil 1. Give a topic (e.g. Essen, Reisen, Medien). The student talks for ~1 minute. Then ask follow-up questions.",
    vocab: ["meiner Meinung nach", "früher", "jetzt", "weil", "normalerweise", "besonders"],
    opener: "Try: open with your opinion, e.g. 'Reisen ist für mich wichtig, weil…'" },
  { id: "a2-speaking-2", title: "Goethe A2: Picture Talk", icon: "🖼️", category: "Exam Prep", level: "A2",
    description: "Teil 2 — describe and comment on a photo.",
    goal: "Describe a typical Goethe A2 photo (e.g. people eating in a restaurant). The student says what's happening + own experience + opinion.",
    vocab: ["Ich sehe…", "im Vordergrund", "im Hintergrund", "vielleicht", "meine Erfahrung", "ich denke"],
    opener: "Try: 'Auf dem Bild sehe ich…'" },
  { id: "a2-speaking-3", title: "Goethe A2: Plan Together", icon: "📅", category: "Exam Prep", level: "A2",
    description: "Teil 3 — plan something with your partner.",
    goal: "You are the exam partner Teil 3: plan an event with the student (city trip, party). They must suggest, agree, disagree, decide. React dynamically.",
    vocab: ["Ich schlage vor…", "Wie wäre es mit…?", "einverstanden", "am besten", "dann treffen wir uns"],
    opener: "Try: 'Ich schlage vor, wir fahren nach…'" },
  { id: "hobbies-exam", title: "Exam Topic: Hobbies", icon: "🎸", category: "Exam Prep", level: "A1",
    description: "The classic exam theme — talk about hobbies.",
    goal: "Classic German exam small-talk: hobbies. How often, who with, since when, why you like it. Common in A1/A2 speaking sections.",
    vocab: ["das Hobby", "spielen", "lesen", "hören", "am Wochenende", "seit"],
    opener: "Try: 'Mein Hobby ist Musik hören.'" },
  { id: "describe-picture", title: "Describe a Picture", icon: "🌆", category: "Exam Prep", level: "A2",
    description: "Practice describing scenes fluently.",
    goal: "Show (describe) simple scenes one by one: a park, a kitchen, a busy street. The student describes in German; you ask about details (Wer? Wo? Was machen sie?).",
    vocab: ["Ich sehe", "links/rechts", "in der Mitte", "die Person", "vielleicht", "es gibt"],
    opener: "Try: 'In der Mitte sehe ich zwei Personen.'" },
  { id: "exam-interview", title: "Full A1 Speaking Mock", icon: "🏁", category: "Exam Prep", level: "A1",
    description: "Complete mini mock: intro + cards + requests.",
    goal: "Run a condensed full Goethe A1 speaking exam: 1) intro questions 2) theme card speaking 3) a request. Then give quick exam-style feedback.",
    vocab: ["die Prüfung", "viel Glück", "noch einmal", "genau", "sehr gut"],
    opener: "Try: just answer the first question — 'Wie heißen Sie?'" },
];

export function getScenario(id: string): Scenario | undefined {
  return SCENARIOS.find((s) => s.id === id);
}

export const SCENARIO_LEVEL_COLORS: Record<string, string> = {
  A1: "lvl-a1",
  A2: "lvl-a2",
  B1: "lvl-b1",
  B2: "lvl-b2",
};
